version: "3"
services:
    nginx:
        build:
            context: ./Mirrors-Nginx
        container_name: nginx
        network_mode: "host"
        restart: always
        volumes:
            - /mirrors/mirrors/:/mirrors/:ro
            - /ssl/:/ssl:ro
    sync:
        build:
            context: ./Mirrors-Sync
        container_name: sync
        network_mode: "host"
        restart: always
        volumes:
            - /mirrors/mirrors:/mirrors
